# Generated by Django 4.0.1 on 2022-01-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('Relationship', models.CharField(choices=[('S', 'single'), ('M', 'married')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=20)),
                ('lang', models.CharField(max_length=50)),
                ('hobbies', models.TextField()),
                ('picture', models.ImageField(upload_to='records')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('door', models.IntegerField()),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('dist', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('institute', models.TextField()),
                ('address', models.TextField()),
                ('started', models.DateField()),
                ('passed', models.DateField()),
                ('gpa', models.IntegerField()),
                ('resume', models.FileField(upload_to='records')),
            ],
        ),
    ]
