# Generated by Django 4.0.1 on 2022-01-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_info_dob_alter_info_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Relationship',
            field=models.CharField(choices=[('S', 'single'), ('M', 'married')], max_length=20, null=True),
        ),
    ]
