# Generated by Django 4.0.1 on 2022-01-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_info_address_alter_info_city_alter_info_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='confirm_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
