# Generated by Django 3.2 on 2022-01-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_info_confirm_password_info_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='course',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='institute',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
