# Generated by Django 3.2 on 2022-01-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=5000, null=True, upload_to='media'),
        ),
    ]
