# Generated by Django 3.2 on 2022-01-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
