# Generated by Django 3.2 on 2022-01-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='productname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product', verbose_name='Product'),
        ),
    ]
