# Generated by Django 3.2 on 2022-01-31 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20220131_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
