# Generated by Django 3.2 on 2022-01-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20220131_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('mobile', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
