# Generated by Django 4.0.1 on 2022-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp21', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnaill'),
        ),
    ]
