# Generated by Django 4.0.1 on 2022-01-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp21', '0002_alter_mymodel_image_alter_mymodel_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='image',
            new_name='photo',
        ),
    ]
